create table if not exists public.settings (
  id int primary key default 1,
  temperature text default '18°C',
  wind text default 'NE 18 km/h',
  forecast text default 'Nuageux',
  vigilance text default 'Jaune',
  amicale text default 'Prochaine réunion : vendredi 19h30 au foyer.',
  twitter_text text default 'Dernier message du SDIS 78 à intégrer ici.',
  ticker text default 'CIS Saint-Arnoult-en-Yvelines — Bonne garde à tous.',
  updated_at timestamptz default now()
);

insert into public.settings (id) values (1) on conflict (id) do nothing;

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'disponible',
  sort_order int default 0
);

insert into public.vehicles (name, status, sort_order) values
('VSAV 31','disponible',1),('VSAV 25','disponible',2),('FPT','disponible',3),
('VSR','disponible',4),('VTU','disponible',5),('CCF','indisponible',6),
('VLHR','disponible',7),('VF','disponible',8),('MPR','indisponible',9)
on conflict do nothing;

create table if not exists public.monthly_events (
  id bigint generated by default as identity primary key,
  type text not null,
  title text not null,
  event_date date not null,
  event_time text default '',
  location text default '',
  sort_order int default 0
);

create table if not exists public.daily_schedule (
  id bigint generated by default as identity primary key,
  time_label text not null,
  title text not null,
  sort_order int default 0
);

insert into public.daily_schedule (time_label, title, sort_order) values
('07h00','Prise de garde',1),('07h30','Vérification véhicules',2),('08h15','Contrôle matériel opérationnel',3),
('10h00','Manœuvre / formation',4),('12h00','Pause repas',5),('14h00','Sport / cohésion',6),
('17h30','Nettoyage remise',7),('19h00','Transmission consignes',8)
on conflict do nothing;

alter table public.settings enable row level security;
alter table public.vehicles enable row level security;
alter table public.monthly_events enable row level security;
alter table public.daily_schedule enable row level security;

create policy "Lecture publique settings" on public.settings for select using (true);
create policy "Lecture publique vehicles" on public.vehicles for select using (true);
create policy "Lecture publique monthly" on public.monthly_events for select using (true);
create policy "Lecture publique daily" on public.daily_schedule for select using (true);

create policy "Admin settings" on public.settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admin vehicles" on public.vehicles for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admin monthly" on public.monthly_events for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admin daily" on public.daily_schedule for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');


ALTER TABLE settings ADD COLUMN IF NOT EXISTS cis_info text;

-- Améliorations affichage / programmation messages
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS cis_info_start timestamptz;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS cis_info_end timestamptz;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS amicale_start timestamptz;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS amicale_end timestamptz;

-- Colonnes déjà utilisées par le planning journalier récent
ALTER TABLE public.daily_schedule ADD COLUMN IF NOT EXISTS recurrence_type text default 'daily';
ALTER TABLE public.daily_schedule ADD COLUMN IF NOT EXISTS weekdays text default 'all';

-- Mode alerte / urgence rapide
CREATE TABLE IF NOT EXISTS public.alert_mode (
  id int primary key default 1,
  enabled boolean default false,
  title text default 'ALERTE OPÉRATIONNELLE',
  message text default 'Consultez les consignes.',
  updated_at timestamptz default now()
);

INSERT INTO public.alert_mode (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.alert_mode ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'alert_mode'
      AND policyname = 'Lecture publique alert_mode'
  ) THEN
    CREATE POLICY "Lecture publique alert_mode"
      ON public.alert_mode
      FOR SELECT
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'alert_mode'
      AND policyname = 'Admin alert_mode'
  ) THEN
    CREATE POLICY "Admin alert_mode"
      ON public.alert_mode
      FOR ALL
      USING (auth.role() = 'authenticated')
      WITH CHECK (auth.role() = 'authenticated');
  END IF;
END $$;
